# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1ea60cc1-7e93-48f5-813d-1daff458a954'
  imageRepository: 'beerservice'
  containerRegistry: 'devregistry2502.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: CmdLine@2
      inputs:
        script: |
          docker build -t beer-service -f .\src\main\Docker\Dockerfile .
          docker push devregistry2502.azurecr.io/beer-service:latest
          copy C:\Users\Admin\Downloads\Compressed\agent\_work\2\s\src\main\Kubernetes\deployment.yaml C:\Users\Admin\Downloads\Compressed\agent\_work\2\a
        workingDirectory: 'C:\Users\Admin\Downloads\Compressed\agent\_work\2\s'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
